### ISSUE TITLE
I can't seem to be able to place the anchor

### ISSUE THREAD

**Issue by JITAJITA** [FranciscoDadone/AnchorSell#2]
When I try to place the anchor, it disappears and goes back to my inventory, I have tried placing it everywhere

**Comment by FranciscoDadone** [comment]
Hello, can you give me more information? Server and version you'r running. If there are errors in the console. Other plugins, etc.

**Comment by JITAJITA** [comment]
I'm running paper 1.17.1 with Vault, Luck Perms (I'm OP), Anchor sell, Chest Shop, CMI Lib, Death Chest, Drop heads, Economy Plus, Galaxy Shop, global market chest, GTA V loading, image on map, images, jobs reborn, lumber jack, No mob griefing, One Player Sleep, plug man, Portable chests, Silk Spawners, Skins restorer, Slimefun, some sort of wireless redstone plugin (I can't remember it's name), and finally world edit
There are no errors related to Anchor Sell in the console

**Comment by FranciscoDadone** [comment]
Check your config under enable-in-worlds to see if the world in where you are trying to place the anchor is listed there. If not, add it.

**Comment by JITAJITA** [comment]
Thank you so much, it's working now
